# syntax=docker/dockerfile:1

## Build
FROM golang:1.17-alpine AS build-stage

WORKDIR /app

# Download necessary Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-gs-ping

## Deploy
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /docker-gs-ping /docker-gs-ping

# EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/docker-gs-ping" ]

